services:
  users-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: users-service
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${USERS_DB_USER}:${USERS_DB_PASSWORD}@${USERS_DB_HOST}:${USERS_DB_PORT}/${USERS_DB_NAME}?client_encoding=utf8
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8000:8000"

  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    container_name: products-service
    restart: unless-stopped
    environment:
      DB_HOST: ${PRODUCTS_DB_HOST}
      DB_PORT: ${PRODUCTS_DB_PORT}
      DB_NAME: ${PRODUCTS_DB_NAME}
      DB_USERNAME: ${PRODUCTS_DB_USER}
      DB_PASSWORD: ${PRODUCTS_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_FOLDER: ${S3_FOLDER}
    ports:
      - "8081:8081"

  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: orders-service
    restart: unless-stopped
    environment:
      PORT: 3003
      MONGO_URI: mongodb://${ORDERS_DB_HOST}:${ORDERS_DB_PORT}/${ORDERS_DB_NAME}
      USER_SERVICE_URL: http://users-service:8000/api/users
      PRODUCT_SERVICE_URL: http://products-service:8081/api/products
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      users-service:
        condition: service_started
      products-service:
        condition: service_started
    ports:
      - "3003:3003"

  aggregator-service:
    build:
      context: ./aggregator-service
      dockerfile: Dockerfile
    container_name: aggregator-service
    restart: unless-stopped
    environment:
      USERS_SERVICE_URL: http://users-service:8000/api/users
      PRODUCTS_SERVICE_URL: http://products-service:8081/api/products
      ORDERS_SERVICE_URL: http://orders-service:3003/api/orders
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      users-service:
        condition: service_started
      products-service:
        condition: service_started
      orders-service:
        condition: service_started
    ports:
      - "8005:8005"

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
      ATHENA_DATABASE: ${ATHENA_DATABASE}
      ATHENA_OUTPUT_LOCATION: ${ATHENA_OUTPUT_LOCATION}
    depends_on:
      orders-service:
        condition: service_started
      products-service:
        condition: service_started
    ports:
      - "8006:8006"
